import { v4 as uuidv4 } from "uuid"; 

function chillHop() {
    return [

        {
            name:"Radio Accordeon Sans Pub",
            artist: "Accordion",
            cover: "https://manuappshome.files.wordpress.com/2020/02/radio-accordeon-sans-pub.png",
            id: uuidv4(),
            color: ["#F24933", "#F9B437"],
            audio: "http://live2.jupinfo.fr:8000/radioaccordeon",
            active: true,
        },
        {
            name:"Top Tonic Accordeon",
            artist: "Accordion",
            cover: "https://manuappshome.files.wordpress.com/2020/02/top-tonic-accordc3a9on.png",
            id: uuidv4(),
            color: ["#D7B0D5", "#CBDFE0"],
            audio: "https://streamingv2.shoutcast.com/TopTonicAccordeon",
            active: false,
        },
        {
            name:"Radio Accordeon Musette",
            artist: "Accordion",
            cover: "https://manuappshome.files.wordpress.com/2020/02/accodeon-generica.png",
            id: uuidv4(),
            color: ["#D7B0D5", "#CBDFE0"],
            audio: "https://live2.jupinfo.fr:8443/radioaccordeon",
            active: false,
        },
        {
            name:"Flon Flon Musette",
            artist: "Accordion",
            cover: "https://manuappshome.files.wordpress.com/2020/02/flon-flon-musette.png",
            id: uuidv4(),
            color: ["#1D2731", "#F17E76"],
            audio: "https://listen.radioking.com/radio/260329/stream/305056",
            active: false,
        },
        {
            name:"Pedazo de acordeon",
            artist: "Accordion",
            cover: "https://manuappshome.files.wordpress.com/2020/02/escucha-a-pedazo-de-acordeon.png",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "http://62.210.38.137:8446/;",
            active: false,
        },
        {
            name:"Radio Plus 104,3 Fm",
            artist: "Accordion",
            cover: "https://manuappshome.files.wordpress.com/2021/07/radio-plus.jpg",
            id: uuidv4(),
            color: ["#845648","#FDFBDF"],
            audio: "https://radioplus2.ice.infomaniak.ch/radioplus.aac",
            active: false,
        },
        {
            name:"Nortenas Inmortales Radio",
            artist: "Accordion",
            cover: "https://manuappshome.files.wordpress.com/2021/07/nortenas-inmortales.png",
            id: uuidv4(),
            color: ["#578CCE", "#E9D6D0"],
            audio: "https://node-07.zeno.fm/26w1f7r5n6duv",
            active: false,
        },
        {
            name:"Radio Studio Souto",
            artist: "Accordion",
            cover: "https://manuappshome.files.wordpress.com/2020/02/radio-studio-souto.png",
            id: uuidv4(),
            color: ["#191516", "#82698E"],
            audio: "https://centova5.transmissaodigital.com:20030/;",
            active: false,
        },
        {
            name:"CONJUNTOS NORTENOS",
            artist: "Accordion",
            cover: "https://manuappshome.files.wordpress.com/2020/02/conjuntos-nortec391os.png",
            id: uuidv4(),
            color: ["#7BC8DD", "#D64A59"],
            audio: "https://14843.live.streamtheworld.com/SAM07AAC220_SC",
            active: false,
        },
        {
            name:"La nueva 88.7 FM",
            artist: "Accordion",
            cover: "https://manuappshome.files.wordpress.com/2020/02/la-nueva-88-7-fm.png",
            id: uuidv4(),
            color: ["#FDE1A9", "#A46874"],
            audio: "http://server.voxstream.net:7106/stream/1/",
            active: false,
        },
        {
            name:"LA RADIO DE TITI",
            artist: "Accordion",
            cover: "https://manuappshome.files.wordpress.com/2020/02/la-radio-de-titi.png",
            id: uuidv4(),
            color: ["#D7B0D5", "#CBDFE0"],
            audio: "https://stream.rcvfm.fr:8000/titi-128k.mp3",
            active: false,
        },
        {
            name:"Infinite Accordion",
            artist: "Accordion",
            cover: "https://manuappshome.files.wordpress.com/2020/02/infinite-accordion.png",
            id: uuidv4(),
            color: ["#1D2731", "#F17E76"],
            audio: "http://streaming.radionomy.com/JamendoLounge",
            active: false,
        },
        {
            name:"RDICI",
            artist: "Accordion",
            cover: "https://manuappshome.files.wordpress.com/2020/02/rdici.png",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "https://radio.pro-fhi.net/flux-njxcsnli/stream2",
            active: false,
        },
        {
            name:"Radio Cagnac",
            artist: "Accordion",
            cover: "https://manuappshome.files.wordpress.com/2020/02/radio-cagnac.png",
            id: uuidv4(),
            color: ["#D7B0D5", "#CBDFE0"],
            audio: "http://2stream.dyndns.org:8000/cagnac_sd.mp3",
            active: false,
        },
        {
            name:"Radio Accordeon France",
            artist: "Accordion",
            cover: "https://manuappshome.files.wordpress.com/2020/02/radio-accordc3a9on.png",
            id: uuidv4(),
            color: ["#1D2731", "#F17E76"],
            audio: "http://live2.jupinfo.fr:8000/radioaccordeon",
            active: false,
        },
        {
            name:"Radio Mensajera 100,5 Fm",
            artist: "Accordion",
            cover: "https://manuappshome.files.wordpress.com/2021/07/radio-mensajera-1005-fm.jpg",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "https://s26.myradiostream.com/:17412/stream/1/",
            active: false,
        },
    ];
}

export default chillHop;

