import { v4 as uuidv4 } from "uuid"; 

function chillHop() {
    return [

        {
            name:"De Corazon A Corazon",
            artist: "Canticos y Alabanzas",
            cover: "https://manuappshome.files.wordpress.com/2020/07/canticos-2.png",
            id: uuidv4(),
            color: ["#F24933", "#F9B437"],
            audio: "https://ia800204.us.archive.org/22/items/DeCorazonACorazon/PalabraEnAccion-DeCorazonAcorazon.mp3",
            active: true,
        },
        {
            name:"Yo Te Amo",
            artist: "Canticos y Alabanzas",
            cover: "https://manuappshome.files.wordpress.com/2020/07/canticos-4.png",
            id: uuidv4(),
            color: ["#D7B0D5", "#CBDFE0"],
            audio: "https://ia800205.us.archive.org/12/items/YoTeAmo_938/PalabraEnAccionYoTeAmo.mp3",
            active: false,
        },
        {
            name:"Cuando Estoy En Tu Casa",
            artist: "Canticos y Alabanzas",
            cover: "https://manuappshome.files.wordpress.com/2020/07/canticos-7.png",
            id: uuidv4(),
            color: ["#D7B0D5", "#CBDFE0"],
            audio: "https://ia800205.us.archive.org/1/items/CuandoEstoyEnTuCasa/Servando-CuandoEstoyEnTuCasa.mp3",
            active: false,
        },
        {
            name:"SUBLIME GRACIA,
            artist: "Canticos y Alabanzas",
            cover: "https://manuappshome.files.wordpress.com/2020/07/canticos-12.png",
            id: uuidv4(),
            color: ["#1D2731", "#F17E76"],
            audio: "https://ia801901.us.archive.org/11/items/himnosycanticos/25%20Himnos%20Favoritos%20-%2003%20-%20SUBLIME%20GRACIA.mp3",
            active: false,
        },
        {
            name:"Cuan Grande Es El",
            artist: "Canticos y Alabanzas",
            cover: "https://manuappshome.files.wordpress.com/2020/07/canticos-11.png",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "https://ia801901.us.archive.org/11/items/himnosycanticos/25%20Himnos%20Favoritos%20-%2001%20-%20CUAN%20GRANDE%20ES%20EL.mp3",
            active: false,
        },
        {
            name:"Oh tu Fidelidad",
            artist: "Canticos y Alabanzas",
            cover: "https://manuappshome.files.wordpress.com/2020/07/canticos-8.png",
            id: uuidv4(),
            color: ["#845648","#FDFBDF"],
            audio: "https://ia801901.us.archive.org/11/items/himnosycanticos/25%20Himnos%20Favoritos%20-%2002%20-%20OH%20TU%20FIDELIDAD.mp3",
            active: false,
        },
        {
            name:"LOORES DAD A CRISTO EL REY",
            artist: "Canticos y Alabanzas",
            cover: "https://manuappshome.files.wordpress.com/2020/07/canticos-5.png",
            id: uuidv4(),
            color: ["#578CCE", "#E9D6D0"],
            audio: "https://ia801901.us.archive.org/11/items/himnosycanticos/25%20Himnos%20Favoritos%20-%2004%20-%20LOORES%20DAD%20A%20CRISTO%20EL%20REY.mp3",
            active: false,
        },
        {
            name:"OH CUAN DULCE",
            artist: "Canticos y Alabanzas",
            cover: "https://manuappshome.files.wordpress.com/2020/07/canticos-10.png",
            id: uuidv4(),
            color: ["#191516", "#82698E"],
            audio: "https://ia801901.us.archive.org/11/items/himnosycanticos/25%20Himnos%20Favoritos%20-%2005%20-%20OH%20CUAN%20GRANDE%20ES%20EL.mp3",
            active: false,
        },
        {
            name:"VICTORIA EN CRISTO",
            artist: "Canticos y Alabanzas",
            cover: "https://manuappshome.files.wordpress.com/2020/07/canticos-9.png",
            id: uuidv4(),
            color: ["#7BC8DD", "#D64A59"],
            audio: "https://ia801901.us.archive.org/11/items/himnosycanticos/25%20Himnos%20Favoritos%20-%2006%20-%20VICTORIA%20EN%20CRISTO.mp3",
            active: false,
        },
        {
            name:"Oh que Amigo",
            artist: "Canticos y Alabanzas",
            cover: "https://manuappshome.files.wordpress.com/2020/07/canticos-6.png",
            id: uuidv4(),
            color: ["#FDE1A9", "#A46874"],
            audio: "https://ia801901.us.archive.org/11/items/himnosycanticos/25%20Himnos%20Favoritos%20-%2007%20-%20OH%20QUE%20AMIGO%20.mp3",
            active: false,
        },
        {
            name:"SANTO,SANTO,SANTO",
            artist: "Canticos y Alabanzas",
            cover: "https://manuappshome.files.wordpress.com/2020/07/canticos-2.png",
            id: uuidv4(),
            color: ["#D7B0D5", "#CBDFE0"],
            audio: "https://ia801901.us.archive.org/11/items/himnosycanticos/25%20Himnos%20Favoritos%20-%2008%20-%20SANTO%2C%20SANTO%2C%20SANTO.mp3",
            active: false,
        },
        {
            name:"TU INCOPARABLE AMOR",
            artist: "Canticos y Alabanzas",
            cover: "https://manuappshome.files.wordpress.com/2020/07/canticos-4.png",
            id: uuidv4(),
            color: ["#1D2731", "#F17E76"],
            audio: "https://ia601901.us.archive.org/11/items/himnosycanticos/25%20Himnos%20Favoritos%20-%2009%20-%20TU%20INCOMPARABLE%20AMOR.mp3",
            active: false,
        },
        {
            name:"LA CRUZ DE JESUS",
            artist: "Canticos y Alabanzas",
            cover: "https://manuappshome.files.wordpress.com/2020/07/canticos-7.png",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "https://ia801901.us.archive.org/11/items/himnosycanticos/25%20Himnos%20Favoritos%20-%2010%20-%20LA%20CRUZ%20DE%20JESUS.mp3",
            active: false,
        },
        {
            name:"Prefiero a Jesus",
            artist: "Canticos y Alabanzas",
            cover: "https://manuappshome.files.wordpress.com/2020/07/canticos-3.png",
            id: uuidv4(),
            color: ["#D7B0D5", "#CBDFE0"],
            audio: "https://ia801901.us.archive.org/11/items/himnosycanticos/25%20Himnos%20Favoritos%20-%2012%20-%20PREFIERO%20A%20JESUS.mp3",
            active: false,
        },
        {
            name:"Jubilosos te adoramos",
            artist: "Canticos y Alabanzas",
            cover: "https://manuappshome.files.wordpress.com/2020/07/canticos-1.png",
            id: uuidv4(),
            color: ["#1D2731", "#F17E76"],
            audio: "https://ia801901.us.archive.org/11/items/himnosycanticos/25%20Himnos%20Favoritos%20-%2013%20-%20JUBILOSOS%20TE%20ADORAMOS.mp3",
            active: false,
        },
        {
            name:"Alcance Salvacion",
            artist: "Canticos y Alabanzas",
            cover: "https://manuappshome.files.wordpress.com/2020/07/canticos-12.png",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "https://ia801901.us.archive.org/11/items/himnosycanticos/25%20Himnos%20Favoritos%20-%2014%20-%20ALCANCE%20SALVACION.mp3",
            active: false,
        },
        {
            name:"EN JESUCRISTO MARTIR DE LA PAZ",
            artist: "Canticos y Alabanzas",
            cover: "https://manuappshome.files.wordpress.com/2020/07/canticos-11.png",
            id: uuidv4(),
            color: ["#D7B0D5", "#CBDFE0"],
            audio: "https://ia801901.us.archive.org/11/items/himnosycanticos/25%20Himnos%20Favoritos%20-%2015%20-%20EN%20JESUCRISTO%20MARTIR%20DE%20PAZ.mp3",
            active: false,
        },
        {
            name:"DULCE ORACION",
            artist: "Canticos y Alabanzas",
            cover: "https://manuappshome.files.wordpress.com/2020/07/canticos-8.png",
            id: uuidv4(),
            color: ["#1D2731", "#F17E76"],
            audio: "https://ia801901.us.archive.org/11/items/himnosycanticos/25%20Himnos%20Favoritos%20-%2016%20-%20DULCE%20ORACION.mp3",
            active: false,
        },
        {
            name:"Oh que tuviera lenguas mil",
            artist: "Canticos y Alabanzas",
            cover: "https://manuappshome.files.wordpress.com/2020/07/canticos-5.png",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "https://ia801901.us.archive.org/11/items/himnosycanticos/25%20Himnos%20Favoritos%20-%2017%20-%20OH%20QUE%20TUVIERA%20LENGUAS%20MIL.mp3",
            active: false,
        },
        {
            name:"A SOLAS",
            artist: "Canticos y Alabanzas",
            cover: "https://manuappshome.files.wordpress.com/2020/07/canticos-10.png",
            id: uuidv4(),
            color: ["#D7B0D5", "#CBDFE0"],
            audio: "https://ia601901.us.archive.org/11/items/himnosycanticos/25%20Himnos%20Favoritos%20-%2018%20-%20A%20SOLAS.mp3",
            active: false,
        },
        {
            name:"TE QUIERO MI SENOR",
            artist: "Canticos y Alabanzas",
            cover: "https://manuappshome.files.wordpress.com/2020/07/canticos-9.png",
            id: uuidv4(),
            color: ["#1D2731", "#F17E76"],
            audio: "https://ia801901.us.archive.org/11/items/himnosycanticos/25%20Himnos%20Favoritos%20-%2019%20-%20TE%20QUIERO%20MI%20SENOR.mp3",
            active: false,
        },
         {
            name:"ROCA DE LA ETERNIDAD",
            artist: "Canticos y Alabanzas",
            cover: "https://manuappshome.files.wordpress.com/2020/07/canticos-6.png",
            id: uuidv4(),
            color: ["#1D2731", "#F17E76"],
            audio: "https://ia801901.us.archive.org/11/items/himnosycanticos/25%20Himnos%20Favoritos%20-%2021%20-%20ROCA%20DE%20LA%20ETERNIDAD.mp3",
            active: false,
        },
         {
            name:"Alma bendice al Senor",
            artist: "Canticos y Alabanzas",
            cover: "https://manuappshome.files.wordpress.com/2020/07/canticos-2.png",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "https://ia801901.us.archive.org/11/items/himnosycanticos/25%20Himnos%20Favoritos%20-%2022%20-%20ALMA%20BENDICE%20AL%20SENOR.mp3",
            active: false,
        },
        {
            name:"PON TUS OJOS EN CRISTO",
            artist: "Canticos y Alabanzas",
            cover: "https://manuappshome.files.wordpress.com/2020/07/canticos-4.png",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "https://ia801901.us.archive.org/11/items/himnosycanticos/25%20Himnos%20Favoritos%20-%2023%20-%20PON%20TUS%20OJOS%20EN%20CRISTO.mp3",
            active: false,
        },
        {
            name:"Tal como soy",
            artist: "Canticos y Alabanzas",
            cover: "https://manuappshome.files.wordpress.com/2020/07/canticos-7.png",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "https://ia801901.us.archive.org/11/items/himnosycanticos/25%20Himnos%20Favoritos%20-%2024%20-%20TAL%20COMO%20SOY.mp3",
            active: false,
        },
        {
            name:"ALABAD AL GRAN REY",
            artist: "Canticos y Alabanzas",
            cover: "https://manuappshome.files.wordpress.com/2020/07/canticos-3.png",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "https://ia801901.us.archive.org/11/items/himnosycanticos/25%20Himnos%20Favoritos%20-%2025%20-%20ALABAD%20AL%20GRAN%20REY.mp3",
            active: false,
        },
        {
            name:"ANTE EL TRONO CELESTIAL",
            artist: "Canticos y Alabanzas",
            cover: "https://manuappshome.files.wordpress.com/2020/07/canticos-1.png",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "https://ia801901.us.archive.org/11/items/himnosycanticos/ANTE%20EL%20TRONO%20CELESTIAL%5B1%5D.mp3",
            active: false,
        },
        {
            name:"Kronehit 90s dance",
            artist: "Canticos y Alabanzas",
            cover: "https://manuappshome.files.wordpress.com/2019/09/kronehit-90s-dance-ac3b1os-90-1.png",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "https://secureonair.krone.at/kronehit21.mp3",
            active: false,
        },
        {
            name:"DnB and EDM - USA",
            artist: "Canticos y Alabanzas",
            cover: "https://manuappshome.files.wordpress.com/2021/12/dnbedm-150.png",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "http://edmdnb.com:8000/radio.mp3",
            active: false,
        },
        {
            name:"Discover Trance Radio",
            artist: "Canticos y Alabanzas",
            cover: "https://manuappshome.files.wordpress.com/2019/09/discover-trance-radio.png",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "http://loki.discovertrance.com/;",
            active: false,
        },
        {
            name:"Q-Dance Amsterdam",
            artist: "Electro-Trance",
            cover: "https://manuappshome.files.wordpress.com/2019/09/q-dance-electro-trance.png",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "http://playerservices.streamtheworld.com/api/livestream-redirect/Q_DANCE.mp3",
            active: false,
        },
        {
            name:"ElectroDanceWorld Radio",
            artist: "ElectroDance",
            cover: "https://manuappshome.files.wordpress.com/2019/09/electrodanceworld-radio-trance.png",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "http://node-24.zeno.fm/g325adzcrm0uv",
            active: false,
        },
        {
            name:"Trancelovers",
            artist: "Trance Music",
            cover: "https://manuappshome.files.wordpress.com/2019/09/trancelovers.png",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "http://stream1.ml0.t4e.dj/trancelovers_high.mp3",
            active: false,
        },
        {
            name:"FM 98.5 Vocal Trance",
            artist: "Trance Music",
            cover: "https://manuappshome.files.wordpress.com/2019/09/fm-98-5-vocal-trance.png",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "http://24.168.84.122:8068/;",
            active: false,
        },
        {
            name:"Radio Espace",
            artist: "Dance",
            cover: "https://manuappshome.files.wordpress.com/2019/09/radio-espace-dance-90-en-tunein.png",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "http://espace-disco.ice.infomaniak.ch/espace-disco-high.mp3",
            active: false,
        },
        {
            name:"Radio 105 - Dance",
            artist: "Dance",
            cover: "https://manuappshome.files.wordpress.com/2019/09/radio-105-dance-90-ac3b1os-90.png",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "http://icy.unitedradio.it/105Dance90.mp3",
            active: false,
        },
        {
            name:"Radio DJ ONE",
            artist: "Dance",
            cover: "https://manuappshome.files.wordpress.com/2022/05/radio-dj-one.png",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "https://stream.djradio.ro/radio/8000/stream.mp3",
            active: false,
        },
        {
            name:"Radio DEEA",
            artist: "Dance",
            cover: "https://manuappshome.files.wordpress.com/2022/05/radio-deea.jpeg",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "https://radiocdn.nxthost.com/radio-deea",
            active: false,
        },
        {
            name:"Eurodance 90",
            artist: "Dance",
            cover: "https://manuappshome.files.wordpress.com/2019/09/eurodance-90-dance-anos-90-house-ac3b1os-90.png",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "http://node-08.zeno.fm/g1u270e2ybruv",
            active: false,
        },
         {
            name:"FFH Eurodance",
            artist: "Dance",
            cover: "https://manuappshome.files.wordpress.com/2019/09/ffh-eurodance-ac3b1os-90.png",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "http://streams.ffh.de/ffhchannels/mp3/hqeurodance.mp3",
            active: false,
        },
         {
            name:"90 Dance Radio Fm",
            artist: "Dance",
            cover: "https://manuappshome.files.wordpress.com/2019/09/generico-dance.jpg",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "https://90s90s.hoerradar.de/90s90s-eurodance-mp3-hq",
            active: false,
        },
         {
            name:"One World Radio",
            artist: "Dance",
            cover: "https://manuappshome.files.wordpress.com/2022/05/one-world-radio.png",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "https://23623.live.streamtheworld.com/OWR_INTERNATIONAL_ADP_SC",
            active: false,
        },
         {
            name:"Radio Oldies Romania",
            artist: "Dance",
            cover: "https://manuappshome.files.wordpress.com/2022/05/radio-oldies-romania.png",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "http://live.radiooldies.ro:9200/stream",
            active: false,
        },
         {
            name:"Radio Party",
            artist: "Dance",
            cover: "https://manuappshome.files.wordpress.com/2022/05/radio-party.png",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "http://partyradio.zapto.org:9964/;",
            active: false,
        },
        {
            name:"OneFM",
            artist: "Dance",
            cover: "https://manuappshome.files.wordpress.com/2022/05/onefm.png",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "https://live.onefm.ro/onefm.aacp",
            active: false,
        },
        {
            name:"Radio Pro-B",
            artist: "Dance",
            cover: "https://manuappshome.files.wordpress.com/2022/05/radio-pro-b.png",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "https://ssl.ascultatare.ro/8888/stream",
            active: false,
        },
        {
            name:"Radio Live247",
            artist: "Dance",
            cover: "https://manuappshome.files.wordpress.com/2022/05/radio-live247.png",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "https://stream11.expo-media.eu/radio/8980/;stream.nsv",
            active: false,
        },
        {
            name:"Psychedelik Drum n Bass",
            artist: "Psychedelik",
            cover: "https://manuappshome.files.wordpress.com/2019/10/psychedelik-drumn-bass-en-tunein.png",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "http://62.210.114.63:8030/playlist.mp3",
            active: false,
        },
        {
            name:"Radio Record Jungle",
            artist: "Jungle-DrumnBass",
            cover: "https://manuappshome.files.wordpress.com/2019/10/radio-record-jungle-drumnbass.png",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "https://hls-01-radiorecord.hostingradio.ru/record-jungle/96/playlist.m3u8",
            active: false,
        },
        {
            name:"Dnb Station",
            artist: "DrumnBass",
            cover: "https://manuappshome.files.wordpress.com/2019/10/dnb-station-en-tunein.png",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "http://dnbstation.com:8000/;",
            active: false,
        },
        {
            name:"Jungletrain",
            artist: "Dance",
            cover: "https://manuappshome.files.wordpress.com/2019/10/dosis-decibel-en-jungletrain-net-en-tunein.png",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "http://stream5.jungletrain.net:8000/;387436630980872stream.nsv",
            active: false,
        },
        {
            name:"Bassjunkees",
            artist: "DrumnBass",
            cover: "https://manuappshome.files.wordpress.com/2019/10/bassjunkees-drumnbass.png",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "http://ducks.and.ponies.listen.bassjunkees.com:8442/;/;7126140696744452stream.nsv",
            active: false,
        },
        {
            name:"BEDLAM DNB",
            artist: "Drum&Bass",
            cover: "https://manuappshome.files.wordpress.com/2019/10/bedlam-dnb-en-tunein.png",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "http://c11.radioboss.fm:8318/stream?type=.mp3",
            active: false,
        },
        {
            name:"Break Pirates",
            artist: "Drum&Bass",
            cover: "https://manuappshome.files.wordpress.com/2019/10/break-pirates-electro-drumnbass.png",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "http://bpstream.hostco.de:3000/;",
            active: false,
        },
        {
            name:"Dubplate Fm Drum Bass Radio",
            artist: "Drum&Bass",
            cover: "https://manuappshome.files.wordpress.com/2019/10/dubplate-fm-drum-bass-radio-drumnbass.png",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "http://sc2.dubplate.fm:5000/DnB/192",
            active: false,
        },
        {
            name:"DirtyBass FM",
            artist: "Drum&Bass",
            cover: "https://manuappshome.files.wordpress.com/2019/10/dirtybass-fm-drumnbass-electro.png",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "http://dirtybass.fm:8000/dirtybass_low.mp3",
            active: false,
        },
        {
            name:"Crazy Bass",
            artist: "Drum&Bass",
            cover: "https://manuappshome.files.wordpress.com/2019/10/crazybass-techno-drumnbass.png",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "https://crazybass.stream.laut.fm/crazybass",
            active: false,
        },
        {
            name:"Radio Nachtflug",
            artist: "Techno",
            cover: "https://manuappshome.files.wordpress.com/2019/10/radio-nachtflug-gc3b3tico-heavy-metal.png",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "http://server26265.streamplus.de/;",
            active: false,
        },
        {
            name:"Drum Base Space",
            artist: "Drum&Bass",
            cover: "https://manuappshome.files.wordpress.com/2019/10/drumbase-space-drumnbass.png",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "http://172.105.0.101/radio/8000/radio.mp3",
            active: false,
        },
        {
            name:"Radio Tube Drum Bass",
            artist: "Drum&Bass",
            cover: "https://manuappshome.files.wordpress.com/2019/10/radio-tube-drum-and-bass-drumnbass.png",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "http://91.232.4.33:7022/stream/1/",
            active: false,
        },
        {
            name:"UTURN RADIO",
            artist: "Drum&Bass",
            cover: "https://manuappshome.files.wordpress.com/2019/10/uturn-radio-drum-and-bass-drumnbass.png",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "http://listen.uturnradio.com/drum_and_bass",
            active: false,
        },
        {
            name:"BassDrive",
            artist: "Drum&Bass",
            cover: "https://manuappshome.files.wordpress.com/2019/10/bassdrive-drumnbass.png",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "http://bassdrive.radioca.st:8702/stream/1/",
            active: false,
        },
        {
            name:"DnB Liquified",
            artist: "Drum&Bass",
            cover: "https://manuappshome.files.wordpress.com/2021/12/d-n-b-liquified-160.png",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "https://antares.dribbcast.com/proxy/dave1?mp=/stream",
            active: false,
        },
        {
            name:"Future Sounds Radio DNB",
            artist: "Drum&Bass",
            cover: "https://manuappshome.files.wordpress.com/2019/10/radio-dnb-en-tunein.png",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "https://streams.radio.co/s03151434c/listen",
            active: false,
        },
        {
            name:"BrokenBeats Atmospheric dnb",
            artist: "Drum&Bass",
            cover: "https://manuappshome.files.wordpress.com/2019/10/brokenbeats-net-atmospheric-dnb-s0urce-en-tunein.png",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "http://brokenbeats.net:8000/tune",
            active: false,
        },
        {
            name:"DNB Noize Radio",
            artist: "Drum&Bass",
            cover: "https://manuappshome.files.wordpress.com/2019/10/dnb-noize-radio-en-tunein.png",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "http://noizemedia.com:8000/dnbnoize",
            active: false,
        },
        {
            name:"Sky Plus DNB",
            artist: "Drum&Bass",
            cover: "https://manuappshome.files.wordpress.com/2019/10/sky-plus-dnb-en-tunein.png",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "https://skymedia-live.bitflip.ee/NRJdnb",
            active: false,
        },
        {
            name:"Dominator Radio",
            artist: "DnB Techno",
            cover: "https://manuappshome.files.wordpress.com/2019/10/dominator-radio.png",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "http://gielisgreat.tk:8000/stream",
            active: false,
        },
        {
            name:"Global Beats FM White Channel",
            artist: "EDM Music",
            cover: "https://manuappshome.files.wordpress.com/2019/10/global-dnb-en-tunein.png",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "http://gbs01.de:7220/;722330734584306stream.nsv",
            active: false,
        },
         {
            name:"Psychedelik Progressive",
            artist: "Psychedelik",
            cover: "https://manuappshome.files.wordpress.com/2019/10/psychedelic-goa-trance-pro-darkspy.png",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "http://62.210.114.63:8010/;",
            active: false,
        },
         {
            name:"BOM Psytrance Radio",
            artist: "Psytrance",
            cover: "https://manuappshome.files.wordpress.com/2019/09/1-fm-bom-psytrance-radio.png",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "http://strm112.1.fm/psytrance_mobile_mp3",
            active: false,
        },
         {
            name:"Psyndora Psytrance",
            artist: "Psytrance",
            cover: "https://manuappshome.files.wordpress.com/2019/09/psyndora-psytrance.png",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "http://cast.magicstreams.gr:9111/stream",
            active: false,
        },
         {
            name:"Psyradio PsyTrance",
            artist: "Psytrance",
            cover: "https://manuappshome.files.wordpress.com/2019/09/psyradio-psytrance.png",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "http://streamer.psyradio.org:8030/;",
            active: false,
        },
         {
            name:"Hirschmilch Psytrance Channel",
            artist: "Psytrance",
            cover: "https://manuappshome.files.wordpress.com/2019/09/hirschmilch-psytrance-channel-electro-trance.png",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "http://hirschmilch.de:7000/psytrance.mp3",
            active: false,
        },
         {
            name:"Schizoid PsychedelicTrance",
            artist: "PsyTrance",
            cover: "https://manuappshome.files.wordpress.com/2019/09/radio-schizoid-psychedelic-trance-trance-electro.png",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "http://94.130.113.214:8000/schizoid",
            active: false,
        },
         {
            name:"Schizoid Progressive",
            artist: "Progressive",
            cover: "https://manuappshome.files.wordpress.com/2021/12/schizoid_progressive-150.png",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "http://94.130.113.214:8000/prog",
            active: false,
        },
         {
            name:"Sunshine live Trance",
            artist: "Trance",
            cover: "https://manuappshome.files.wordpress.com/2019/09/sunshine-live-trance-trance-electro.png",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "http://stream.sunshine-live.de/trance/mp3-128/radiode/",
            active: false,
        },
         {
            name:"1Mix Trance",
            artist: "Trance",
            cover: "https://manuappshome.files.wordpress.com/2019/09/1-mix-radio-trance.png",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "http://fr3.1mix.co.uk:8000/320",
            active: false,
        },
         {
            name:"GOA Channel ONE",
            artist: "Trance",
            cover: "https://manuappshome.files.wordpress.com/2019/09/goa-channel-one-.png",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "http://goa-channel-one.stream.laut.fm/goa-channel-one",
            active: false,
        },
         {
            name:"Toksyna FM Psytrance",
            artist: "Psytrance",
            cover: "https://manuappshome.files.wordpress.com/2019/09/toksyna-fm-psytrance-electro-trance.png",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "http://s01.toksyna.fm:8030/stream/1/",
            active: false,
        },
         {
            name:"A State of Trance",
            artist: "Trance",
            cover: "https://manuappshome.files.wordpress.com/2019/09/a-state-of-trance-radio-show.jpg",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "http://de-hz-fal-stream07.rautemusik.fm/trance",
            active: false,
        },
         {
            name:"Radio Boost",
            artist: "Trance",
            cover: "https://manuappshome.files.wordpress.com/2020/03/radio-boost-en-tunein.png",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "http://149.202.22.75:8066/;",
            active: false,
        },
         {
            name:"TranceBase FM",
            artist: "Trance",
            cover: "https://manuappshome.files.wordpress.com/2019/09/trancebase-fm-en-tunein.png",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "https://listener1.mp3.tb-group.fm/trb.mp3",
            active: false,
        },
         {
            name:"Absolute Trance Euro Radio",
            artist: "Trance",
            cover: "https://manuappshome.files.wordpress.com/2022/01/absolute-trance-radio.png",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "http://strm112.1.fm/trance_mobile_mp3",
            active: false,
        },
         {
            name:"Zone-mix",
            artist: "Trance",
            cover: "https://manuappshome.files.wordpress.com/2019/09/zone-mix.png",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "http://zone-mix.stream.laut.fm/zone-mix",
            active: false,
        },
         {
            name:"Puls Trance",
            artist: "Trance",
            cover: "https://manuappshome.files.wordpress.com/2019/09/pulstrance-electro-trance.png",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "http://193.200.42.211/pulstranceHD.mp3",
            active: false,
        },
         {
            name:"ETN Trance Toronto",
            artist: "Trance",
            cover: "https://manuappshome.files.wordpress.com/2019/09/etn-trance.png",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "http://8.43.48.6:8120/;;",
            active: false,
        },
        {
            name:"Intense Radio",
            artist: "Electro House",
            cover: "https://manuappshome.files.wordpress.com/2019/09/intense-radio-electro-house.png",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "http://stream.intenseradio.net:8000/live",
            active: false,
        },
        {
            name:"TrancePulse FM",
            artist: "Trance",
            cover: "https://manuappshome.files.wordpress.com/2019/09/trancepulse-fm-electro-drumnbass.png",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "https://stream.trance.ie:8443/stream",
            active: false,
        },
        {
            name:"Radio Caprice Vocal Trance",
            artist: "Trance",
            cover: "https://manuappshome.files.wordpress.com/2022/01/radio-caprice-vocal-trance-150.png",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "http://79.120.39.202:8000/vocaltrance",
            active: false,
        },
        {
            name:"1.FM Amsterdam Trance",
            artist: "Trance",
            cover: "https://manuappshome.files.wordpress.com/2022/01/1-fm-amsterdam-trance.png",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "http://sc-atr.1.fm:7700/",
            active: false,
        },
        {
            name:"Trance Athena",
            artist: "Trance",
            cover: "https://manuappshome.files.wordpress.com/2019/09/trance-athena.png",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "http://cast.streams.ovh:8008/stream",
            active: false,
        },
        {
            name:"Prysm Trance",
            artist: "Trance",
            cover: "https://manuappshome.files.wordpress.com/2019/09/prysm-trance-trance.png",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "http://n20a-eu.rcs.revma.com/wnad06xqknruv",
            active: false,
        },
        {
            name:"Digital Impulse",
            artist: "Psy Trance",
            cover: "https://manuappshome.files.wordpress.com/2019/09/digital-impulse-psy-trance.png",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "http://orion.shoutca.st:8049/stream",
            active: false,
        },
        {
            name:"FM Trance Buenos Aires",
            artist: "Trance",
            cover: "https://manuappshome.files.wordpress.com/2019/09/fm-trance.png",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "http://streaming01.dwservers.net:8100/;",
            active: false,
        },
        {
            name:"Club Angelic Radio",
            artist: "Trance",
            cover: "https://manuappshome.files.wordpress.com/2019/09/club-angelic-radio.png",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "http://trance.angelic.fm/hq",
            active: false,
        },
        {
            name:"Dance Fm live Trance",
            artist: "Trance",
            cover: "https://manuappshome.files.wordpress.com/2019/09/dancefmlive-trance.png",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "https://broadcast.dancefmlive.com/radio/8010/radio.mp3",
            active: false,
        },
        {
            name:"Toronto Global Radio",
            artist: "Trance",
            cover: "https://manuappshome.files.wordpress.com/2019/09/toronto-global-radio-trance.png",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "http://london-dedicated.myautodj.com:8126/stream",
            active: false,
        },
        {
            name:"AH.FM - Leading Trance Radio",
            artist: "Trance",
            cover: "https://manuappshome.files.wordpress.com/2019/09/fm-leading-trance-radio.png",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "http://relay.ah.fm/;",
            active: false,
        },
        {
            name:"24 House Radio",
            artist: "House",
            cover: "https://manuappshome.files.wordpress.com/2022/05/24-house-radio.jpg",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "https://strw1.openstream.co/1487",
            active: false,
        },
        {
            name:"Ibiza Beats Radio",
            artist: "House",
            cover: "https://manuappshome.files.wordpress.com/2019/10/ibiza-beats-radio.png",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "https://silveran.radioca.st/stream",
            active: false,
        },
        {
            name:"Minimalmix Radio",
            artist: "House",
            cover: "https://manuappshome.files.wordpress.com/2019/10/minimalmix-radio-dub-electro.png",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "https://minimalmix.radioca.st/media",
            active: false,
        },
        {
            name:"BeachGrooves Radio",
            artist: "House",
            cover: "https://manuappshome.files.wordpress.com/2019/10/beachgrooves-radio.png",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "http://stream.beachgrooves.com:8000/;stream/1/;808485038155367stream.nsv",
            active: false,
        },
        {
            name:"Deep House Lounge",
            artist: "House",
            cover: "https://manuappshome.files.wordpress.com/2019/10/deep-house-lounge-radio.png",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "http://198.15.94.34:8006/stream",
            active: false,
        },
        {
            name:"HouseTime Radio FM",
            artist: "House",
            cover: "https://manuappshome.files.wordpress.com/2022/06/housetime-fm.png",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "http://listener2.mp3.tb-group.fm/ht.mp3",
            active: false,
        },
        {
            name:"MABU Beatz Radio Tech House",
            artist: "Tech House",
            cover: "https://manuappshome.files.wordpress.com/2019/10/mabu-beatz-radio-tech-house-techno-house.png",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "http://78.47.31.164:8002/techhouse",
            active: false,
        },
        {
            name:"Ibiza Beach Radio House",
            artist: "House",
            cover: "https://manuappshome.files.wordpress.com/2019/09/ibiza-beach-radio-house-techno.png",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "http://174.36.206.197:7272/stream",
            active: false,
        },
        {
            name:"Strictly House DeepDownDirty",
            artist: "Techno House",
            cover: "https://manuappshome.files.wordpress.com/2019/10/strictly-house-deepdowndirty-techno-house.png",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "http://radio.strictly.house:9500/stream",
            active: false,
        },
        {
            name:"06AM Ibiza Underground Radio",
            artist: "Electro House",
            cover: "https://manuappshome.files.wordpress.com/2019/10/06am-ibiza-underground-electro-house.png",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "https://streams.radio.co/sd1bcd1376/listen",
            active: false,
        },
        {
            name:"Seduction Dance Tunes Radio",
            artist: "Electro House",
            cover: "https://manuappshome.files.wordpress.com/2019/10/seduction-dance-tunes-radio-electro-house.png",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "https://24streams.me/8057/stream",
            active: false,
        },
        {
            name:"Vicious Radio",
            artist: "House",
            cover: "https://manuappshome.files.wordpress.com/2019/10/vicious-radio.png",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "http://radiorobot.es:8000/nacionalweb",
            active: false,
        },
        {
            name:"Electro Radio",
            artist: "Electro House",
            cover: "https://manuappshome.files.wordpress.com/2019/09/generico-dance1.jpg",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "http://stream.electroradio.fm/stream",
            active: false,
        },
        {
            name:"Holiday Gym Radio",
            artist: "Electro Dance",
            cover: "https://manuappshome.files.wordpress.com/2019/10/holiday-gym-radio.png",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "http://holidaygym.emitironline.com/",
            active: false,
        },
        {
            name:"Costa Del Mar",
            artist: "Deep-House",
            cover: "https://manuappshome.files.wordpress.com/2019/10/costa-del-mar-deep-house.png",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "http://stream.cdm-deephouse.com:8012/stream-mp3-Deep_autodj",
            active: false,
        },
        {
            name:"MABU Beatz Radio Dub",
            artist: "Techno House",
            cover: "https://manuappshome.files.wordpress.com/2019/10/mabu-beatz-radio-dub-techno-techno.png",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "http://78.47.31.164:8002/dub",
            active: false,
        },
        {
            name:"I LOVE 2 DANCE - House DJ-Mix",
            artist: "House EDM",
            cover: "https://manuappshome.files.wordpress.com/2019/10/i-love-2-dance-house-edm-dj-mix.png",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "http://stream08.iloveradio.de/iloveradio2.mp3",
            active: false,
        },
        {
            name:"Loca FM Techhouse",
            artist: "Techno House",
            cover: "https://manuappshome.files.wordpress.com/2019/10/loca-fm-techhouse-house-techno1.png",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "http://s02.fjperezdj.com:8046/live",
            active: false,
        },
        {
            name:"Lounge Downbeat radio",
            artist: "Lounge House",
            cover: "https://manuappshome.files.wordpress.com/2019/10/lounge-chillout-house.png",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "http://lounge.stream.laut.fm/lounge",
            active: false,
        },
        {
            name:"54house fm",
            artist: "House",
            cover: "https://manuappshome.files.wordpress.com/2019/09/54house-fm-house.png",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "http://62.138.2.128:8000/stream",
            active: false,
        },
        {
            name:"Raute Musik House",
            artist: "Electro House",
            cover: "https://manuappshome.files.wordpress.com/2019/09/raute-musik-house-electro-house.png",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "http://de-hz-fal-stream07.rautemusik.fm/house",
            active: false,
        },
    ];
}

export default chillHop;

